# Generated by Django 4.2.7 on 2023-11-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('project', models.CharField(max_length=35)),
                ('change', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pendiente'), ('Approved', 'Aprovada'), ('Rejected', 'Rechazada')], default='Pending', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
